some additions
zledtriac/CDP1802Emu pull request #1
Opened 2022-11-01 19:23 UTC by MsAlPatina

2022-11-06 20:14 UTC, dlt-v requested changes
Please check code comments.

2022-11-06 20:14 UTC, dlt-v commented on cdp1802app/src/MemoryView.js
> +	 var popupseveraty = "success";
Don't use vars, use let and const. For details look for ES6 documentation

2022-11-06 20:14 UTC, dlt-v commented on cdp1802app/src/MemoryView.js
> +  var checkedIN2 = checked;
Don't use vars

2022-11-06 20:14 UTC, dlt-v commented on cdp1802app/src/MemoryView.js
> +
Fix the white spaces, please be consistent

2022-11-06 20:14 UTC, dlt-v commented on cdp1802app/src/RAMSYSTEM.js
> +
Use consistent white spaces, have you thought of using a formatter?

2022-11-06 20:14 UTC, dlt-v commented on cdp1802app/src/MemoryView.js
> +  var checkedIN2 = "disabled";
Don't use vars, be consistent

2022-11-06 20:14 UTC, dlt-v commented on cdp1802app/src/MemoryView.js
> +
Why some many white spaces? Fix it

2022-11-06 20:14 UTC, dlt-v commented on cdp1802app/src/MemoryView.js
> +		 popupseveraty = "error";
consistent tabs please

2022-11-06 20:15 UTC, dlt-v reviewed
Check comments for changes

2022-11-06 20:15 UTC, dlt-v commented on cdp1802app/src/MemoryView.js
> +
white space

2022-11-06 20:15 UTC, dlt-v commented on cdp1802app/src/MemoryView.js
> +
spaces

2022-11-06 20:15 UTC, dlt-v commented on cdp1802app/src/RAMSYSTEM.js
> +
spaces

2022-11-06 20:15 UTC, dlt-v commented on cdp1802app/src/RAMSYSTEM.js
> +	  <p aaa />
?

2022-11-06 20:18 UTC, dlt-v commented
Code not main branch ready, imo. Inconsistent, mix of pre-ES6 and new ES6+ code in same files.
Console logs are not for main branch. Leave them in debug before merge.
Please consider using a formatter to format your white spaces.
It would be useful to write some comments about what the code does.
Cheers,
- Delta

2022-11-08 07:41 UTC, closed without merging

2022-11-08 07:42 UTC, MsAlPatina commented
> Code not main branch ready, imo. Inconsistent, mix of pre-ES6 and new ES6+ code in same files.
> Console logs are not for main branch. Leave them in debug before merge.
> Please consider using a formatter to format your white spaces.
> It would be useful to write some comments about what the code does.
> Cheers,
> - Delta

Alrighty, maybe can ya suggest an good formatter?

2022-11-08 10:16 UTC, dlt-v commented
> 

I use Prettier